-- SQL Script to create the Tamweel Results table
-- Paste this into your Supabase SQL Editor

-- 1. Create the table
CREATE TABLE IF NOT EXISTS tamweel_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE,
    password TEXT,
    profession TEXT,
    profession_category TEXT,
    avg_monthly_income_jod FLOAT8,
    credit_score INT,
    risk_level TEXT,
    decision TEXT,
    approved_amount_jod INT,
    reason TEXT,
    key_strengths TEXT[], -- Array of strings
    key_risks TEXT[],      -- Array of strings
    score_breakdown JSONB, -- Stores income_stability, bill_history, etc.
    generated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS) - Optional for prototype
-- ALTER TABLE tamweel_results ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow anyone to read/write for the prototype
-- CREATE POLICY "Allow public access" ON tamweel_results FOR ALL USING (true);

-- 4. Sample Insert for testing
INSERT INTO tamweel_results (
    name, profession, profession_category, avg_monthly_income_jod, 
    credit_score, risk_level, decision, approved_amount_jod, reason
) VALUES (
    'Anas', 'Software Engineer', 'freelance', 850.0, 
    78, 'Low', 'Approved', 600, 
    'يظهر ملفك المالي التزاماً جيداً واستقراراً في الدخل الشهري.'
);
